---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: inferentia-inf2
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        provisioner: inferentia-inf2
        hub.jupyter.org/node-purpose: user
    spec:  
      nodeClassRef:
        name: inferentia-inf2    
      requirements:
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: [${azs}d]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot", "on-demand"]
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: ["inf2.24xlarge", "inf2.48xlarge"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      taints:
        - key: "aws.amazon.com/neuroncore"
          value: "true"
          effect: "NoSchedule"
        - key: "aws.amazon.com/neuron"
          value: "true"
          effect: "NoSchedule"
        - key: hub.jupyter.org/dedicated # According to optimization docs https://z2jh.jupyter.org/en/latest/administrator/optimization.html
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"
    disruption:
      consolidationPolicy: WhenEmpty
      consolidateAfter: 300s  

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: inferentia-inf2
  namespace: karpenter
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        encrypted: true
  role: "${eks_cluster_id}-karpenter-node"      
  subnetSelectorTerms:
    - tags:
        Name: ${eks_cluster_id}-private*
  securityGroupSelectorTerms:
    - name: "${eks_cluster_id}-node*"
  tags:
    InstanceType: "inferentia"
