---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}d]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-size"
      operator: In
      values: ["xlarge", "2xlarge", "4xlarge", "8xlarge", "16xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  labels:
    provisioner: default
    workload: rayhead
  limits:
    resources:
      cpu: 1000
      memory: 20000Gi
  #ttlSecondsAfterEmpty: 120 # optional, but never scales down if not set

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: true
  subnetSelector:
    Name: ${eks_cluster_id}-private*
  securityGroupSelector:
    Name: ${eks_cluster_id}-node*
  tags:
    managed-by: "karpenter"
    intent: "apps"
    Name: "karpenter-node-default"
