---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: inferentia-inf2
  namespace: karpenter
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}c]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["inf2.24xlarge", "inf2.48xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  providerRef:
    name: inferentia-inf2
  labels:
    provisioner: inferentia-inf2
    hub.jupyter.org/node-purpose: user
  taints:
    - key: aws.amazon.com/neuroncore
      value: "true"
      effect: "NoSchedule"
    - key: aws.amazon.com/neuron
      value: "true"
      effect: "NoSchedule"
  #ttlSecondsAfterEmpty: 300 # optional, but never scales down if not set

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: inferentia-inf2
  namespace: karpenter
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
  subnetSelector:
    Name: ${eks_cluster_id}-private*
  securityGroupSelector:
    Name: ${eks_cluster_id}-node*
  tags:
    InstanceType: "inferentia"
